version: '3.8'

services:
  fastapi-app:
    container_name: sssp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_TOKEN_EXPIRE_MINUTES: ${JWT_TOKEN_EXPIRE_MINUTES}
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sssp-database:
        condition: service_healthy

  sssp-database:
    image: mysql:8.0
    container_name: sssp-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: sssp
      MYSQL_ROOT_PASSWORD: sssppassword
      MYSQL_DATABASE: sssp_database
      MYSQL_PASSWORD: sssppassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
