services:
  fastapi-app:
    container_name: sssp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db  # 데이터베이스가 필요한 경우 정의
    
  # 예시: PostgreSQL 데이터베이스 추가
  db:
    container_name: sssp-database
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
